Repository PrestaShop/statsforecast, pull requests merged in 2022-01, with the labels that each got.

#23 Add build release
  .github/workflows/build-release.yml
Labels: enhancement

#24 Set tab property
  statsforecast.php
Labels: bug

#25 Missing cast for amount data
  statsforecast.php
Labels: QA ✔️
